name: Auto update Verify result

on:
  issues:
    types: [edited]

jobs:
  update-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Update Verify result when Status is Done
        uses: ChristineChau-ASUS/For-Test@v2
        with:
          # 要更新的欄位
          field-name: 'Verify result'
          # 更新值
          value: 'Pass'
          # 目標 project card
          project-url: ${{ github.event.issue.html_url }}
          # 只在 Status 欄位為 Done 時更新
          if: ${{ github.event.issue.labels.* == 'Done' }}
